#!/usr/bin/env bash
set -Eeuo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  printf 'Usage: %s COURSE LECTURE_NUMBER\n' "$(basename "$0")" >&2
  printf 'Create a new LaTeX lecture note under <course>/lectures/lecture_NN.tex\n' >&2
  printf 'COURSE may be a number (118), a slug (math118, stat150), or spelled out (Math 118, Stat 150).\n' >&2
  printf 'Examples:\n' >&2
  printf '  %s 118 3\n' "$(basename "$0")" >&2
  printf '  %s Math118 1\n' "$(basename "$0")" >&2
  printf '  %s stat150 2\n' "$(basename "$0")" >&2
}

if [[ $# -ne 2 ]]; then
  usage
  exit 2
fi

course_input="$1"
lecture_number="$2"

if [[ ! "$lecture_number" =~ ^[0-9]+$ ]]; then
  printf 'Lecture number must be an integer: %s\n' "$lecture_number" >&2
  exit 2
fi

# ---------- Course registry ----------
# Maps a course number to: folder, human-readable label, and long name.
# Add a line here when you enroll in a new course.
course_folder=""
course_label=""
course_name=""
register() {
  local num="$1" folder="$2" label="$3" name="$4"
  printf '%s\t%s\t%s\t%s\n' "$num" "$folder" "$label" "$name"
}

COURSES="$(register 104 math104 "Math 104"  "Real Analysis")"
COURSES+="$(printf '\n%s' "$(register 110 math110 "Math 110" "Abstract Linear Algebra")")"
COURSES+="$(printf '\n%s' "$(register 113 math113 "Math 113" "Abstract Algebra")")"
COURSES+="$(printf '\n%s' "$(register 118 math118 "Math 118" "Fourier Analysis")")"
COURSES+="$(printf '\n%s' "$(register 150 stat150 "Stat 150" "Stochastic Processes")")"

# Normalise the input to a bare course number (digits only).
course_num="$(printf '%s' "$course_input" | tr -cd '[:digit:]')"

if [[ -z "$course_num" ]]; then
  printf 'Could not read a course number from: %s\n' "$course_input" >&2
  exit 2
fi

while IFS=$'\t' read -r num folder label name; do
  if [[ "$num" == "$course_num" ]]; then
    course_folder="$folder"
    course_label="$label"
    course_name="$name"
    break
  fi
done <<<"$COURSES"

# Fallback for an unregistered course: infer the subject from the input.
if [[ -z "$course_folder" ]]; then
  if printf '%s' "$course_input" | grep -qi 'stat'; then
    course_folder="stat${course_num}"
    course_label="Stat ${course_num}"
  else
    course_folder="math${course_num}"
    course_label="Math ${course_num}"
  fi
  course_name="$course_label"
fi

lecture_padded="$(printf '%02d' "$((10#$lecture_number))")"
lectures_dir="$REPO_ROOT/$course_folder/lectures"
target="$lectures_dir/lecture_${lecture_padded}.tex"

if [[ -e "$target" ]]; then
  printf 'Already exists: %s\n' "$target" >&2
  exit 1
fi

mkdir -p "$lectures_dir"
cat > "$target" <<EOF
% !TEX program = lualatex
% Generated by new_lecture_note.sh
\documentclass[11pt]{article}

\usepackage{fontspec}
\usepackage{microtype}
\usepackage{mathtools,amssymb,amsfonts,amsthm,bm}
\usepackage{enumitem}
\usepackage{booktabs,array,xcolor}
\usepackage{geometry,fancyhdr,setspace}
\usepackage[hidelinks]{hyperref}
\usepackage[nameinlink,noabbrev]{cleveref}

\geometry{margin=1in,headheight=15pt}
\setstretch{1.12}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0.55em plus 0.12em minus 0.08em}
\setlength{\abovedisplayskip}{0.8em plus 0.2em minus 0.1em}
\setlength{\belowdisplayskip}{0.8em plus 0.2em minus 0.1em}
\allowdisplaybreaks[3]
\setlist{leftmargin=*,topsep=0.35em,itemsep=0.15em,parsep=0pt}

% ---------- Metadata ----------
\newcommand{\studentname}{Keshav Ramamurthy}
\newcommand{\coursename}{$course_label}
\newcommand{\courselongname}{$course_name}
\newcommand{\lecturenumber}{$lecture_padded}
\newcommand{\lecturetitle}{Lecture $lecture_padded}
\newcommand{\lecturedate}{\today}

% ---------- Reusable notation ----------
\newcommand{\N}{\mathbb{N}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\Q}{\mathbb{Q}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\F}{\mathbb{F}}
\newcommand{\K}{\mathbb{K}}
\newcommand{\E}{\mathbb{E}}
\newcommand{\Prob}{\mathbb{P}}
\newcommand{\1}{\mathbf{1}}
\newcommand{\eps}{\varepsilon}
\newcommand{\dd}{\,\mathrm{d}}
\newcommand{\abs}[1]{\left\lvert#1\right\rvert}
\newcommand{\norm}[1]{\left\lVert#1\right\rVert}
\newcommand{\ip}[2]{\left\langle#1,#2\right\rangle}
\newcommand{\set}[1]{\left\{#1\right\}}
\newcommand{\given}{\,\middle\vert\,}
\newcommand{\indep}{\perp\!\!\!\perp}
\newcommand{\lto}{\longrightarrow}
\newcommand{\deriv}[2]{\frac{\mathrm{d}#1}{\mathrm{d}#2}}
\newcommand{\pderiv}[2]{\frac{\partial#1}{\partial#2}}
\DeclareMathOperator{\Aut}{Aut}
\DeclareMathOperator{\Hom}{Hom}
\DeclareMathOperator{\Ker}{ker}
\DeclareMathOperator{\im}{im}
\DeclareMathOperator{\rank}{rank}
\DeclareMathOperator{\nullity}{nullity}
\DeclareMathOperator{\Span}{span}
\DeclareMathOperator{\Var}{Var}
\DeclareMathOperator{\Cov}{Cov}

% ---------- Note environments ----------
\newtheoremstyle{notestyle}{0.7em}{0.7em}{\itshape}{}{}{\bfseries}{.5em}{}
\theoremstyle{notestyle}
\newtheorem{theorem}{Theorem}[section]
\newtheorem{lemma}[theorem]{Lemma}
\newtheorem{proposition}[theorem]{Proposition}
\newtheorem{corollary}[theorem]{Corollary}
\theoremstyle{definition}
\newtheorem{definition}[theorem]{Definition}
\newtheorem{example}[theorem]{Example}
\newtheorem{remark}[theorem]{Remark}
\newenvironment{claim}{\par\noindent\textbf{Claim.}\ }{\par}
\newenvironment{idea}{\par\noindent\textit{Idea.}\ }{\par}
\newenvironment{proofsketch}{\par\noindent\textbf{Proof sketch.}\ }{\par}

% ---------- Header ----------
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\coursename}
\fancyhead[C]{\lecturetitle}
\fancyhead[R]{\studentname}
\fancyfoot[C]{\thepage}

\title{\vspace{-1.5em}\textbf{\coursename\ -- \lecturetitle}}
\author{\studentname}
\date{\lecturedate}

\begin{document}
\maketitle

\section{Main idea}
\textit{Write the one-sentence point of today's lecture here.}

\section{Definitions and notation}
\begin{definition}[First definition]
Write the definition and one sentence explaining why it matters.
\end{definition}

\section{Claims, theorems, and proof sketches}
\begin{claim}
State the claim in one precise sentence.
\end{claim}

\begin{proofsketch}
Record the key idea, the first useful equation, and the step that still needs checking.
\end{proofsketch}

\section{Examples and calculations}
\begin{example}[Lecture example]
Write the setup, the calculation, and the conclusion.
\end{example}

\section{Questions and follow-up}
\begin{itemize}
  \item What is still unclear?
  \item Which exercise or reading should I revisit?
  \item TODO:
\end{itemize}

\end{document}
EOF

printf 'Created %s\n' "$target"
printf 'Open it with: nvim %q\n' "$target"
printf 'Build + push with: ./sync.sh\n'
